server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
     server:
       git:
         uri: https://github.com/claubermar/ServersYML-bootcamp.git
       default-label: main
#       search-paths:
#       - '*service*'
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/